### ISSUE TITLE
lol, been there. 

### ISSUE THREAD

**Issue by PatrickAlphaC** [Dash-Monkey/ethodyssey#7]
<img width="138" alt="Screen Shot 2021-08-16 at 3 36 24 PM" src="https://user-images.githubusercontent.com/54278053/129619820-a552132e-e529-443a-b5ee-98839a10a5ab.png">

Glad you were able to pull through to submit!

**Comment by thisispalash** [comment]
Hahaha yes the deadline snuck up on me, despite the extension 😅

I submitted something but I doubt I'd win anything. Though, good honing for the idea though and there's always more hacks!
